services:
  - type: web
    name: webapp
    env: docker
    repo: https://github.com/b12k/vueltimate-boilerplate.git
    region: frankfurt
    plan: free
    branch: master
    numInstances: 1
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
  - type: redis
    name: cache
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
    maxmemoryPolicy: allkeys-lru
